<template>
  <div class="loadingio-spinner-dual-ring-f0gdt3ehiy7">
    <div class="ldio-7g1nhjm5exo">
      <div></div>
      <div><div></div></div>
    </div>
  </div>
</template>
<script setup>
defineProps({
  color: {
    type: String,
    default: "#001",
  },
});
</script>
<style>
@keyframes ldio-7g1nhjm5exo {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-7g1nhjm5exo div {
  box-sizing: border-box !important;
}
.ldio-7g1nhjm5exo > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 16px solid #eee;
  border-color: v-bind(color) transparent v-bind(color) transparent;
  animation: ldio-7g1nhjm5exo 1s linear infinite;
}
.ldio-7g1nhjm5exo > div:nth-child(2) {
  border-color: transparent;
}
.ldio-7g1nhjm5exo > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-7g1nhjm5exo > div:nth-child(2) div:before,
.ldio-7g1nhjm5exo > div:nth-child(2) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: v-bind(color);
  border-radius: 50%;
  box-shadow: 0 128px 0 0 v-bind(color);
}
.ldio-7g1nhjm5exo > div:nth-child(2) div:after {
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 v-bind(color);
}
.loadingio-spinner-dual-ring-f0gdt3ehiy7 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-7g1nhjm5exo {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-7g1nhjm5exo div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
